# Generated by Django 3.2.6 on 2021-08-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=200)),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
    ]
